---
title: "SentimentAnalysisProject"
author: "Condag, Gagante, Gonzaga"
date: "10/12/2024"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(dplyr)
library(syuzhet)
library(ggplot2)
library(tidyverse)
library(stringr)
library(tm)
library(scales)
library(readr)

iniTweets <- read.csv("tweetsDF.csv")

tweetsDf <- iniTweets

```



```{r}
cleanTweets <- tweetsDf %>%
  mutate(text = str_to_lower(text),                     
         text = str_remove_all(text, "http\\S+"),
         text = str_remove_all(text, "[^\\w\\s]"),
         text = str_remove_all(text, "#\\w+"),
         text = str_remove_all(text, "@\\w+"),          
         text = str_remove_all(text, "\\d+"),    
         text = str_squish(text),                      
         sentiment = get_sentiment(text, method = "bing"))

write.csv(cleanTweets, "cleaned_tweets.csv", row.names = FALSE)

```

```{r}
cleanTweets <- cleanTweets %>%
  mutate(date = ymd_hms(created)) %>%  
  mutate(hour = hour(date))

byHour <- cleanTweets %>%
  group_by(day = as.Date(date), hour) %>%
  summarise(tweet_count = n(), .groups = "drop")

day1 <- byHour %>% filter(day == unique(day)[1])
day2 <- byHour %>% filter(day == unique(day)[2])
day3 <- byHour %>% filter(day == unique(day)[3])

all_days <- bind_rows(
  day1 %>% mutate(day_label = paste("Day", 1)),
  day2 %>% mutate(day_label = paste("Day", 2)),
  day3 %>% mutate(day_label = paste("Day", 3))
)


ggplot(all_days, aes(x = hour, y = tweet_count, group = day, color = as.factor(day))) +
  geom_line(size = 1) +
  geom_point() +
  scale_x_continuous(breaks = seq(0, 23, by = 1)) + 
  labs(
    title = "Tweet Counts by Hour",
    x = "Hour of the Day",
    y = "Number of Tweets",
    color = "Date"
  ) +
  theme_minimal()

```



```



